name: Check Lint

on:
  workflow_dispatch:
  push:
    branches:
    - main
  schedule:
  # Run every sunday at 00:00 AM.
    - cron: "0 0 * * 0"
  pull_request:
    branches: [main]
    paths:
      - 'README.md'
      - '.github/workflows/main.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
#      - name: Awesome linter
#        run: npx awesome-lint
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          # Check only README.md
          args: README.md
          # Use markdown as output format (alternative is json)
          format: markdown
          # Fail action on broken links
          fail: true
